### ISSUE TITLE
Remove __init__.py from keboola folder.

### ISSUE THREAD

**Issue by davidesner** [keboola/python-component#38]
`keboola` is a native namespace package, the init was added in https://github.com/keboola/python-component/commit/f0380867fb6749e97fbb65ae17e763d16cce22a5 and was not spotted by review. This will may make all other keboola native namespace packages unusable. with this one

**Comment by bakobako** [comment]
@davidesner https://github.com/keboola/python-component/pull/40

**Comment by bakobako** [comment]
Solved in https://github.com/keboola/python-component/releases/tag/1.4.0
